env:
  global:
    - CC_TEST_REPORTER_ID=44193afda4ab5eed237422631e68118dd9b73b3977890ea1c89efe28eb4c04d4

language: node_js

node_js:
    - "node"
    - "10"
    - "8"

sudo: false

git:
    submodules: false

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - yarn install

script:
    - yarn test

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
