# Use an official Node runtime as a parent image
FROM node:alpine

# Set the working directory to /home/node/app
WORKDIR /home/node/app

# Install npm packages
COPY package.json ./
COPY yarn.lock ./
RUN yarn install

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run app.py when the container launches
CMD ["yarn", "start"]
